name: Simple CI/CD Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Repository Files
        run: ls -la  # Lists all files in the repo for debugging

      - name: Run Basic Command
        run: echo "CI/CD pipeline executed successfully!"
