name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Docker Installation
        run: docker --version

      - name: Build Docker Image
        run: docker build -t my-python-app:latest .

      - name: Run Container and Test
        run: |
          docker run --rm -d --name test-container my-python-app:latest
          sleep 5  # Wait for the container to start
          docker logs test-container
          docker stop test-container

  push-to-docker-hub:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Image
        run: |
          docker tag my-python-app:latest my-dockerhub-username/my-python-app:latest
          docker push my-dockerhub-username/my-python-app:latest

  deploy:
    runs-on: self-hosted
    needs: push-to-docker-hub
    steps:
      - name: Pull Latest Docker Image
        run: docker pull my-dockerhub-username/my-python-app:latest

      - name: Stop and Remove Old Container
        run: docker stop app-container || true && docker rm app-container || true

      - name: Run New Container
        run: |
          docker run -d --name app-container -p 80:5000 my-dockerhub-username/my-python-app:latest
