name: CI with Docker on Self-Hosted Runner

on: [push, pull_request]

jobs:
  docker-job:
    runs-on: self-hosted  # Uses your EC2 self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Docker Installation
        run: docker --version

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Run Docker Container
        run: |
          docker run --rm -d --name my-container my-app:latest

      - name: List Running Containers
        run: docker ps

      - name: Stop and Remove Container
        run: docker stop my-container
