name: CI with Docker on Self-Hosted Runner

on: [push, pull_request]

jobs:
  docker-job:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Files
        run: ls -alh

      - name: Build Docker Image
        run: docker build -t my-python-app:latest .

      - name: Run Docker Container
        run: docker run --rm -d --name my-container my-python-app:latest

      - name: List Running Containers
        run: docker ps

      - name: Stop and Remove Container
        run: docker stop my-container
